[package]
name = "final_project"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
